### ISSUE TITLE
Re-work SafeWrapper default_handler to log.error instead of Airbrake

### ISSUE THREAD

**Issue by samandmoore** [Betterment/test_track_rails_client#9]
The errors that we catch inside of [`SafeWrapper`](https://github.com/Betterment/test_track_rails_client/blob/master/app/models/test_track/analytics/safe_wrapper.rb) are from analytics client libraries. As such, it doesn't make very much sense to send them over to Airbrake as they are likely to be temporary runtime failures (e.g. http connection issues) and not fixable software bugs.

Also, given that we have the ability to specify our own custom `error_handler` (in the analytics `SafeWrapper`) via a lambda, there is no need to keep the Airbrake code in the default configuration. If someone really wants to log errors coming out of their analytics library integration, then they can configure the `error_handler` on their custom analytics client.

_edited: to add clarification_

**Comment by ceslami** [comment]
👋 

Very interested in the analytics library aspect of this, as timeouts in the Mixpanel client have been frequenting our error tracker. 

Do you think it should be coupled to removing Airbrake?

**Comment by jmileham** [comment]
So you're not calling for removal of Airbrake support in general, are you? Because many uses of Airbrake are to alert on software quality issues in the consuming app code - failing to use `#vary` or `#ab` correctly in ways that we want to gloss over for the end user's benefit (i.e. don't break the UX just because the app code is inconsistent with the split configuration). I spose we could lose the airbrake coupling for those use cases by simply raising in a new thread and letting whatever error notifier you have Just Work. Seems a little weird, but maybe that'd be a way to eliminate that explicit coupling.

**Comment by ceslami** [comment]
To clarify: I don't have a particular opinion whether we should remove Airbrake, but I definitely think we should prevent our analytics clients from raising.

**Comment by jmileham** [comment]
We do prevent them from raising, that's actually what SafeWrapper does. We just also Airbrake explicitly as a side effect, which is what @samandmoore is proposing pulling.

**Comment by ceslami** [comment]
Got it -- my bad.

**Comment by ceslami** [comment]
Re: analytics clients raising: at one point I thought we decided to log when there are analytics client errors. We use Airbrake in other places, and maybe that usage is subject to conversation, but we might already have our answer to how we want to handle analytics library errors.

**Comment by ceslami** [comment]
Sorry for hijacking the thread -- I think we're on the same page

**Comment by samandmoore** [comment]
Sorry if that last bit of the issue was unclear.

When I said, "there is no need to keep the Airbrake code," I was speaking specifically of the line of code here: https://github.com/Betterment/test_track_rails_client/blob/master/app/models/test_track/analytics/safe_wrapper.rb#L28

I think that removing Airbrake in favor of a generic error catcher solution should be discussed separately.

**Comment by samandmoore** [comment]
fixed by #12
